### ISSUE TITLE
使用ESRally压测ElasticSearch性能 | 架构师修炼之道

### ISSUE THREAD

**Issue by tianmingxing** [tianmingxing/tianmingxing.com-gitalk#40]
https://tianmingxing.com/2019/07/02/%E4%BD%BF%E7%94%A8ESRally%E5%8E%8B%E6%B5%8BElasticSearch%E6%80%A7%E8%83%BD/#more 

 123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657------------------------------------------------------    _______             __   _____   / __

**Comment by rljie** [comment]
你好，我的ES是7.2.0版本，做了xpack的加密，esrally要怎么测试加密的ES？需要配置什么，或运行时带什么参数吗？

**Comment by tianmingxing** [comment]
在esrally连接es时配置认证信息就可以了，具体参考esrally文档：https://esrally.readthedocs.io/en/stable/command_line_reference.html

![image](https://user-images.githubusercontent.com/5615719/64469695-39065b80-d169-11e9-8a21-fd7b86c46c62.png)

**Comment by rljie** [comment]
现在执行此命令：
esrally  --target-hosts=12.19.24.92:9200  --pipeline=benchmark-only --client-options="basic_auth_user:'elastic',basic_auth_password:'123456',use_ssl:true,verify_certs:true,ca_certs:'/home/elasticsearch/client-ca.cer',client_cert:'/home/elasticsearch/client.cer',client_key:'/home/elasticsearch/client.key',timeout:120"  --test-mode


报错：该日志内容是rally.log文件
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/esrally/rally.py", line 514, in dispatch_sub_command
    race(cfg)
  File "/usr/local/python3/lib/python3.6/site-packages/esrally/rally.py", line 432, in race
    with_actor_system(lambda c: racecontrol.run(c), cfg)
  File "/usr/local/python3/lib/python3.6/site-packages/esrally/rally.py", line 460, in with_actor_system
    runnable(cfg)
  File "/usr/local/python3/lib/python3.6/site-packages/esrally/rally.py", line 432, in <lambda>
    with_actor_system(lambda c: racecontrol.run(c), cfg)
  File "/usr/local/python3/lib/python3.6/site-packages/esrally/racecontrol.py", line 427, in run
    raise e
  File "/usr/local/python3/lib/python3.6/site-packages/esrally/racecontrol.py", line 424, in run
    pipeline(cfg)
  File "/usr/local/python3/lib/python3.6/site-packages/esrally/racecontrol.py", line 79, in __call__
    self.target(cfg)
  File "/usr/local/python3/lib/python3.6/site-packages/esrally/racecontrol.py", line 352, in benchmark_only
    return race(cfg, external=True)
  File "/usr/local/python3/lib/python3.6/site-packages/esrally/racecontrol.py", line 306, in race
    raise exceptions.RallyError("Got an unexpected result during benchmarking: [%s]." % str(result))
esrally.exceptions.RallyError: ('Got an unexpected result during benchmarking: [None].', None)


#该日志内容，是根据esrally开发团队的提示输出的
2019-09-07 04:07:32.271697 p19628 I    Remote ActorAddr-(T|:44996) closed connection before ack received at ActorAddr-(T|:33583) for TransportIntent(ActorAddr-(T|:44996)-pending-ExpiresIn_0:04:59.990639-<class 'esrally.racecontrol.Setup'>-<esrally.racecontrol.Setup object at 0x7f83fc46ed30>-quit_0:04:59.990579)
2019-09-07 04:07:32.306596 p19628 I    ConnRefused to ActorAddr-(T|:44996); declaring as DeadTarget.
2019-09-07 04:07:32.309253 p19628 I    ConnRefused to ActorAddr-(T|:44996); declaring as DeadTarget.




 



------------------ 原始邮件 ------------------
发件人: "Terrence"<notifications@github.com>; 
发送时间: 2019年9月7日(星期六) 中午12:15
收件人: "xiaoxing598/tianmingxing.com-gitalk"<tianmingxing.com-gitalk@noreply.github.com>; 
抄送: "&#x2121;虚实&#x266C; 憧憬〃"<1042310705@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [xiaoxing598/tianmingxing.com-gitalk] 使用ESRally压测ElasticSearch性能 | 架构师修炼之道 (#40)




在esrally连接es时配置认证信息就可以了，具体参考esrally文档：https://esrally.readthedocs.io/en/stable/command_line_reference.html
